AWSTemplateFormatVersion: 2010-09-09
Description: "Pac-Man Overflow stack"

Parameters:
  KeyPair:
    Description: Private SSH KeyPair
    Type: AWS::EC2::KeyPair::KeyName

Resources:
  SSHSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Enable SSH access via port 22
      SecurityGroupIngress:
        - CidrIp: 0.0.0.0/0
          FromPort: 22
          IpProtocol: tcp
          ToPort: 22

  EC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      KeyName: !Ref KeyPair
      ImageId: ami-0b0ea68c435eb488d
      InstanceType: t2.micro
      Monitoring: true
      SecurityGroups:
        - !Ref SSHSecurityGroup
      UserData: !Base64 |
        #!/bin/bash -ex
        # put your script here
        echo "Hello, World" > test.txt

  ElasticIP:
    Type: AWS::EC2::EIP
    Properties:
      InstanceId: !Ref EC2Instance

Outputs:
  IPAddress:
    Description: Elastic IP Address associated with EC2 Instance
    Value: !Ref ElasticIP