name: cd

# TODO: change this 
on:
  push:
    branches:
      - ci-cd

permissions:
  id-token: write

env:
  REGION: us-east-1
  STACK_NAME: pacman-overflow
  KEY_PAIR: pacman-overflow-gh-action
  KEY_FILE: pacman-overflow-gh-action.dem

jobs:
  build:
    runs-on: ubuntu-latest
    environment: pacman-overflow
    steps:
      - name: Checkout repo
        uses: actions/checkout@master

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: caloverflow
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Get Image tag
        id: get_image_tag
        run: |
          echo "::set-output name=DOCKER_IMAGE::caloverflow/pacman-overflow:$(jq -r .version package.json)"

      - name: Build and push image
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: "${{ steps.get_image_tag.DOCKER_IMAGE }}"

  deploy:
    needs: build
    environment: pacman-overflow
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@master

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ secrets.IAM_ROLE_ARN }}
          aws-region: ${{ env.REGION }}

      - name: Deploy ${{ env.STACK_NAME }} stack
        run: |
          sam deploy --stack-name $STACK_NAME --region $REGION --parameter-overrides KeyPair=$KEY_PAIR --no-fail-on-empty-changeset
      
      - name: Deploy to EC2 Instance
        env:
          DOCKER_IMAGE: ${{ steps.get_image_tag.DOCKER_IMAGE }}
        run: |
          echo "Docker Image: ${{ env.DOCKER_IMAGE }}"
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ${{ env.KEY_FILE }}
          chmod 600 ${{ env.KEY_FILE }}
          echo "Secret in ${{ env.KEY_FILE }}"

          EC2_IP_ADDRESS=$(aws cloudformation describe-stacks --stack-name $STACK_NAME --region $REGION --query 'Stacks[0].Outputs[?OutputKey==`IPAddress`].OutputValue' --output text)
          echo $EC2_IP_ADDRESS

          ssh -i $KEY_FILE -o "StrictHostKeyChecking no" ubuntu@$EC2_IP_ADDRESS "
          echo \"running docker pull ${{ env.DOCKER_IMAGE }}\"
          docker pull ${{ env.DOCKER_IMAGE }}

          # docker run -p 3000:3000 ${{ env.DOCKER_IMAGE }}
          "
          echo "ssh completed successfully"
