name: ci

on:
  pull_request:
    branches:
      - master

jobs:
  acceptance:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@master
      
      - name: Install Node
        uses: actions/setup-node@v2
        with:
          node-version: '16.14.2'

      - name: Install dependencies
        run: npm ci

      - name: Run linter
        run: npm run lint
      
      - name: Run tests
        run: npm run test
